name: npxxx

on: workflow_dispatch

jobs:
  run-debug:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git User
        run: |
          git config --global user.name "bimuafaq"
          git config --global user.email "133272416+bimuafaq@users.noreply.github.com"

      - name: Initialize Environment
        run: |
          npm i -g opencode-ai@latest
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=np-three --accept-routes --ssh          

      - name: Keep Alive for SSH
        run: |
          while true; do sleep 300; done

      - name: Disconnect Tailscale
        if: always()
        run: sudo tailscale logout
